# Generated by Django 2.2.6 on 2019-11-02 20:34
from django.db import migrations


def apply_add_admin_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    admins_group = Group.objects.create(name=u"admins")

    CustomUser = apps.get_model("users", "CustomUser")
    staff = CustomUser.objects.filter(is_staff=True)
    admins_group.user_set.add(*staff)


def revert_add_admin_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    admins_group = Group.objects.filter(name__in=[u"admins"])
    admins_group.user_set.clear()
    admins_group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("users", "0004_customuser_remove_uuid_null"),
    ]

    operations = [migrations.RunPython(apply_add_admin_group, revert_add_admin_group)]
